services:
  app:
    build: .
    container_name: taxi_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
   environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: "no"

  mysql:
    image: mysql:8.0
    container_name: taxi_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: TWlcdNdeajfiOBmyCBEyPrpqtEbrefpM
    volumes:
      - taxi_db:/var/lib/mysql
    restart: always

volumes:
  taxi_db:
