services:
  app:
    build: .
    container_name: taxi_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: TWlcdNdeajfiOBmyCBEyPrpqtEbrefpM
    restart: "no"

  mysql:
    image: mysql:8.0
    container_name: taxi_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: TWlcdNdeajfiOBmyCBEyPrpqtEbrefpM
    volumes:
      - taxi_db:/var/lib/mysql
    restart: always

volumes:
  taxi_db:
